type = block
data = green_lantern
name = Зеленый Фонарь
colum = Декор
matchBlocks = lantern, soul_lantern
texture = customblocklayer:cbl/green_lantern
texture.item = customblocklayer:cbl/item/green_lantern
