type = block
data = black_concrete_wall
name = Стена из Черного бетона
colum = Цветные Блоки
matchBlocks = stone_brick_wall, cobblestone_wall, andesite_wall, diorite_wall, granite_wall, brick_wall, deepslate_wall
texture = minecraft:block/black_concrete
