type = block
data = acacia_bark_stairs
name = Ступеньки из коры акации
colum = Полноценная Древесина
matchBlocks = oak_stairs, spruce_stairs, birch_stairs, jungle_stairs, acacia_stairs, dark_oak_stairs, mangrove_stairs, cherry_stairs, quartz_stairs, stone_stairs
texture = customblocklayer:cbl/logs/acacia_log
texture.side = customblocklayer:cbl/logs/acacia_log
texture.top = customblocklayer:cbl/logs/acacia_log
texture.bottom = customblocklayer:cbl/logs/acacia_log
