type = block
data = jungle_bark_slab
name = Плита из коры тропического дерева
colum = Полноценная Древесина
matchBlocks = oak_slab, spruce_slab, birch_slab, jungle_slab, acacia_slab, dark_oak_slab, mangrove_slab, cherry_slab, quartz_slab, stone_slab
texture = customblocklayer:cbl/logs/jungle_log
texture.side = customblocklayer:cbl/logs/jungle_log
texture.top = customblocklayer:cbl/logs/jungle_log
texture.bottom = customblocklayer:cbl/logs/jungle_log
