type = block
data = warped_bark_fence
name = Забор из искаженной коры
colum = Полноценная Древесина
matchBlocks = crimson_fence, warped_fence, oak_fence, spruce_fence, birch_fence, jungle_fence, acacia_fence, dark_oak_fence, mangrove_fence, cherry_fence
texture = customblocklayer:cbl/logs/warped_stem
texture.side = customblocklayer:cbl/logs/warped_stem
texture.top = customblocklayer:cbl/logs/warped_stem
texture.bottom = customblocklayer:cbl/logs/warped_stem
