type = block
data = warped_bark_slab
name = Плита из искаженной коры
colum = Полноценная Древесина
matchBlocks = crimson_slab, warped_slab, oak_slab, spruce_slab, birch_slab, jungle_slab, acacia_slab, dark_oak_slab, mangrove_slab, cherry_slab, quartz_slab, stone_slab
texture = customblocklayer:cbl/logs/warped_stem
texture.side = customblocklayer:cbl/logs/warped_stem
texture.top = customblocklayer:cbl/logs/warped_stem
texture.bottom = customblocklayer:cbl/logs/warped_stem
