type = block
data = warped_bark_stairs
name = Ступеньки из искаженной коры
colum = Полноценная Древесина
matchBlocks = crimson_stairs, warped_stairs, oak_stairs, spruce_stairs, birch_stairs, jungle_stairs, acacia_stairs, dark_oak_stairs, mangrove_stairs, cherry_stairs, quartz_stairs, stone_stairs
texture = customblocklayer:cbl/logs/warped_stem
texture.side = customblocklayer:cbl/logs/warped_stem
texture.top = customblocklayer:cbl/logs/warped_stem
texture.bottom = customblocklayer:cbl/logs/warped_stem
