type = block
data = red_lantern
name = Красный Фонарь
colum = Декор
matchBlocks = lantern, soul_lantern
texture = customblocklayer:cbl/red_lantern
texture.item = customblocklayer:cbl/item/red_lantern
