type = block
data = cherry_bark_wall
name = Ограда из коры вишни
colum = Полноценная Древесина
matchBlocks = stone_brick_wall, cobblestone_wall, andesite_wall, diorite_wall, granite_wall, brick_wall, deepslate_wall
texture = customblocklayer:cbl/logs/cherry_log
texture.side = customblocklayer:cbl/logs/cherry_log
texture.top = customblocklayer:cbl/logs/cherry_log
texture.bottom = customblocklayer:cbl/logs/cherry_log
