type = block
data = crimson_bark_slab
name = Плита из багровой коры
colum = Полноценная Древесина
matchBlocks = crimson_slab, warped_slab, oak_slab, spruce_slab, birch_slab, jungle_slab, acacia_slab, dark_oak_slab, mangrove_slab, cherry_slab, quartz_slab, stone_slab
texture = customblocklayer:cbl/logs/crimson_stem
texture.side = customblocklayer:cbl/logs/crimson_stem
texture.top = customblocklayer:cbl/logs/crimson_stem
texture.bottom = customblocklayer:cbl/logs/crimson_stem
