type = block
data = jungle_bark_fence
name = Забор из коры тропического дерева
colum = Полноценная Древесина
matchBlocks = oak_fence, spruce_fence, birch_fence, jungle_fence, acacia_fence, dark_oak_fence, mangrove_fence, cherry_fence
texture = customblocklayer:cbl/logs/jungle_log
texture.side = customblocklayer:cbl/logs/jungle_log
texture.top = customblocklayer:cbl/logs/jungle_log
texture.bottom = customblocklayer:cbl/logs/jungle_log
