type = vertical_slab
data = oak_vertical_slab
name = Вертикальная дубовая плита
colum = Полноценная Древесина
matchBlocks = iron_trapdoor, oak_trapdoor, spruce_trapdoor, birch_trapdoor, jungle_trapdoor, acacia_trapdoor, dark_oak_trapdoor, mangrove_trapdoor, cherry_trapdoor, crimson_trapdoor, warped_trapdoor
texture = minecraft:block/oak_planks
