type = vertical_slab
data = yellow_concrete_vertical_slab
name = Вертикальная плита из Желтого бетона
colum = Цветные Блоки
matchBlocks = iron_trapdoor, oak_trapdoor, spruce_trapdoor, birch_trapdoor, jungle_trapdoor, acacia_trapdoor, dark_oak_trapdoor, mangrove_trapdoor, cherry_trapdoor, crimson_trapdoor, warped_trapdoor
texture = minecraft:block/yellow_concrete
