type = block
data = base_crate
name = Деревянный Ящик
colum = Декор
matchBlocks = barrel
texture = customblocklayer:cbl/base_crate
texture.side = customblocklayer:cbl/base_crate
texture.top = customblocklayer:cbl/base_crate
texture.bottom = customblocklayer:cbl/base_crate
texture.top.open = customblocklayer:cbl/base_crate
