type = block
data = tall_shadow_plant
name = Высокое Теневое Растение
colum = Растения
matchBlocks = rose_bush, sunflower, lilac, peony, large_fern, tall_grass
texture.top = customblocklayer:cbl/tall_shadow_plant_top
texture.bottom = customblocklayer:cbl/tall_shadow_plant_bottom
