type = block
data = brown_concrete_wall
name = Стена из Коричневого бетона
colum = Цветные Блоки
matchBlocks = stone_brick_wall, cobblestone_wall, andesite_wall, diorite_wall, granite_wall, brick_wall, deepslate_wall
texture = minecraft:block/brown_concrete
