type = block
data = birch_bark_fence_gate
name = Калитка из коры березы
colum = Полноценная Древесина
matchBlocks = oak_fence_gate, spruce_fence_gate, birch_fence_gate, jungle_fence_gate, acacia_fence_gate, dark_oak_fence_gate, mangrove_fence_gate, cherry_fence_gate
texture = customblocklayer:cbl/logs/birch_log
texture.side = customblocklayer:cbl/logs/birch_log
texture.top = customblocklayer:cbl/logs/birch_log
texture.bottom = customblocklayer:cbl/logs/birch_log
