type = block
data = crimson_bark_wall
name = Ограда из багровой коры
colum = Полноценная Древесина
matchBlocks = stone_brick_wall, cobblestone_wall, andesite_wall, diorite_wall, granite_wall, brick_wall, deepslate_wall
texture = customblocklayer:cbl/logs/crimson_stem
texture.side = customblocklayer:cbl/logs/crimson_stem
texture.top = customblocklayer:cbl/logs/crimson_stem
texture.bottom = customblocklayer:cbl/logs/crimson_stem
