type = block
data = dark_oak_bark_wall
name = Ограда из коры темного дуба
colum = Полноценная Древесина
matchBlocks = stone_brick_wall, cobblestone_wall, andesite_wall, diorite_wall, granite_wall, brick_wall, deepslate_wall
texture = customblocklayer:cbl/logs/dark_oak_log
texture.side = customblocklayer:cbl/logs/dark_oak_log
texture.top = customblocklayer:cbl/logs/dark_oak_log
texture.bottom = customblocklayer:cbl/logs/dark_oak_log
