type = block
data = mangrove_bark_wall
name = Ограда из коры мангрового дерева
colum = Полноценная Древесина
matchBlocks = stone_brick_wall, cobblestone_wall, andesite_wall, diorite_wall, granite_wall, brick_wall, deepslate_wall
texture = customblocklayer:cbl/logs/mangrove_log
texture.side = customblocklayer:cbl/logs/mangrove_log
texture.top = customblocklayer:cbl/logs/mangrove_log
texture.bottom = customblocklayer:cbl/logs/mangrove_log
