type = block
data = warped_bark_fence_gate
name = Калитка из искаженной коры
colum = Полноценная Древесина
matchBlocks = crimson_fence_gate, warped_fence_gate, oak_fence_gate, spruce_fence_gate, birch_fence_gate, jungle_fence_gate, acacia_fence_gate, dark_oak_fence_gate, mangrove_fence_gate, cherry_fence_gate
texture = customblocklayer:cbl/logs/warped_stem
texture.side = customblocklayer:cbl/logs/warped_stem
texture.top = customblocklayer:cbl/logs/warped_stem
texture.bottom = customblocklayer:cbl/logs/warped_stem
