type = chest
data = acacia_chest
name = Акациевый сундук
colum = Контейнеры
matchBlocks = chest, trapped_chest
texture = cbl/chest/acacia_chest
texture.left = cbl/chest/acacia_chest_left
texture.right = cbl/chest/acacia_chest_right
