type = chest
data = birch_chest
name = Березовый сундук
colum = Контейнеры
matchBlocks = chest, trapped_chest
texture = cbl/chest/birch_chest
texture.left = cbl/chest/birch_chest_left
texture.right = cbl/chest/birch_chest_right
