type = chest
data = oak_chest
name = Дубовый сундук
colum = Контейнеры
matchBlocks = chest, trapped_chest
texture = cbl/chest/oak_chest
texture.left = cbl/chest/oak_chest_left
texture.right = cbl/chest/oak_chest_right
