type = vertical_slab
data = dark_oak_bark_vertical_slab
name = Вертикальная плита из Коры тёмного дуба
colum = Полноценная Древесина
matchBlocks = iron_trapdoor, oak_trapdoor, spruce_trapdoor, birch_trapdoor, jungle_trapdoor, acacia_trapdoor, dark_oak_trapdoor, mangrove_trapdoor, cherry_trapdoor, crimson_trapdoor, warped_trapdoor
texture = cbl/logs/dark_oak_log
