type = block
data = dark_oak_bark_fence
name = Забор из коры темного дуба
colum = Полноценная Древесина
matchBlocks = oak_fence, spruce_fence, birch_fence, jungle_fence, acacia_fence, dark_oak_fence, mangrove_fence, cherry_fence
texture = customblocklayer:cbl/logs/dark_oak_log
texture.side = customblocklayer:cbl/logs/dark_oak_log
texture.top = customblocklayer:cbl/logs/dark_oak_log
texture.bottom = customblocklayer:cbl/logs/dark_oak_log
