type = block
data = magic_crate
matchBlocks = oak_planks, spruce_planks, birch_planks, stone, oak_stairs, cobblestone_stairs, oak_slab, stone_slab
texture.top = crate_top.png
texture.bottom = crate_bottom.png
texture.side = crate_side.png
