type = chest
data = bamboo_chest
name = Бамбуковый сундук
colum = Контейнеры
matchBlocks = chest, trapped_chest
texture = cbl/chest/bamboo_chest
texture.left = cbl/chest/bamboo_chest_left
texture.right = cbl/chest/bamboo_chest_right
