type = chest
data = cherry_chest
name = Вишневый сундук
colum = Контейнеры
matchBlocks = chest, trapped_chest
texture = cbl/chest/cherry_chest
texture.left = cbl/chest/cherry_chest_left
texture.right = cbl/chest/cherry_chest_right
