type = chest
data = mangrove_chest
name = Мангровый сундук
colum = Контейнеры
matchBlocks = chest, trapped_chest
texture = cbl/chest/mangrove_chest
texture.left = cbl/chest/mangrove_chest_left
texture.right = cbl/chest/mangrove_chest_right
