type = chest
data = spruce_chest
name = Еловый сундук
colum = Контейнеры
matchBlocks = chest, trapped_chest
texture = cbl/chest/spruce_chest
texture.left = cbl/chest/spruce_chest_left
texture.right = cbl/chest/spruce_chest_right
