type = chest
data = warped_chest
name = Искаженный сундук
colum = Контейнеры
matchBlocks = chest, trapped_chest
texture = cbl/chest/warped_chest
texture.left = cbl/chest/warped_chest_left
texture.right = cbl/chest/warped_chest_right
