type = chest
data = dark_oak_chest
name = Сундук из темного дуба
colum = Контейнеры
matchBlocks = chest, trapped_chest
texture = cbl/chest/dark_oak_chest
texture.left = cbl/chest/dark_oak_chest_left
texture.right = cbl/chest/dark_oak_chest_right
