type = chest
data = jungle_chest
name = Тропический сундук
colum = Контейнеры
matchBlocks = chest, trapped_chest
texture = cbl/chest/jungle_chest
texture.left = cbl/chest/jungle_chest_left
texture.right = cbl/chest/jungle_chest_right
