# ==========================================
# CustomBlockLayer Plugin Configuration
# ==========================================

storage:
  # Тип хранилища метаданных кастомных блоков:
  # "pdc"    - Нативное хранение в PersistentDataContainer чанка (Рекомендуется, 0 настроек, авто-бэкапы вместе с миром)
  # "sqlite" - Хранение в локальной базе данных SQLite (blocks.db)
  type: "pdc"

network:
  # Радиус в блоках для отправки обновления установки/ломания блоков игрокам
  broadcast_radius: 128
