type = block
data = gray_lantern
name = Серый Фонарь
colum = Декор
matchBlocks = lantern, soul_lantern
texture = customblocklayer:cbl/gray_lantern
texture.item = customblocklayer:cbl/item/gray_lantern
