type = chest
data = crimson_chest
name = Багровый сундук
colum = Контейнеры
matchBlocks = chest, trapped_chest
texture = cbl/chest/crimson_chest
texture.left = cbl/chest/crimson_chest_left
texture.right = cbl/chest/crimson_chest_right
