type = chest
data = iron_chest
name = Железный сундук
colum = Контейнеры
matchBlocks = chest, trapped_chest
texture = cbl/chest/iron_chest
texture.left = cbl/chest/iron_chest_left
texture.right = cbl/chest/iron_chest_right
