type = block
data = metal_container
name = Металлический Контейнер
colum = Декор
matchBlocks = barrel
texture = customblocklayer:cbl/metal_container_side
texture.side = customblocklayer:cbl/metal_container_side
texture.top = customblocklayer:cbl/metal_container_top
texture.bottom = customblocklayer:cbl/metal_container_top
texture.top.open = customblocklayer:cbl/metal_container_top_open
