type = block
data = shadow_plant
name = Теневое Растение
colum = Растения
matchBlocks = poppy, dandelion, allium, azure_bluet, cornflower, fern, short_grass
texture = customblocklayer:cbl/shadow_plant
