type = block
data = purple_concrete_wall
name = Стена из Фиолетового бетона
colum = Цветные Блоки
matchBlocks = stone_brick_wall, cobblestone_wall, andesite_wall, diorite_wall, granite_wall, brick_wall, deepslate_wall
texture = minecraft:block/purple_concrete
